### ISSUE TITLE
Vechtdal - Raalte crop-r API: Well-Known-Text to geojson

### ISSUE THREAD

**Issue by GertS** [FarmHackNL/FarmHack#7]
Hi,

Suppose I have a request like: 
`curl "https://www.crop-r.com/api/v1/cropfield/?format=json&sessionid=xxxx"`
How do I convert the response to a format which I can use in qgis or leaflet like geojson?

**Comment by ndkv** [comment]
You'll have to parse the response, extract the geometry and construct a GeoJSON file. 

In Python this will look something like:

``` python
from shapely.wkt import loads
from shapely.geometry import mapping

out = {'type': 'FeatureCollection', 'features': []}

# response contains the returned JSON object
for cropfield in response['objects']
    id = cropfield['id']
    geom = loads(cropfield['geometry'])

    out['features'].append('properties': {'id': id}, 'type': 'Feature', 'geometry': mapping(geom))'

# write out to a .geojson file
```

**Comment by GertS** [comment]
Thanks! That is very helpful. I'll let you guys know when I have something useful to show!

**Comment by ndkv** [comment]
Ok, please share your working conversion script with us in `challengers/verchtdal/scripts`. Thanks!
